### PR TITLE
Update schedule

### LINKED ISSUE #63: Update schedule
We changed the schedule (refer to Lukas) internally, it should be updated on the website as well.

### PR DESCRIPTION
**Pull request by jonashering**
Close #63 

Guess it's better to have some time between end of hacking and lunch, so I scheduled it for 11 AM. Any thoughts on dis?

~~Also thought it might be good to add we're issuing tickets before the deadline as well.~~

### CODE REVIEW

**Comment by FWirtz** [comment]
@jonashering sorry for the delay, just discussing your change requests with @lheilmann rn.

Not sure if the extra hour is needed - what would participants do in that hour?

Also, we should probably mention the friday event.

**Comment by jonashering** [comment]
Agree 👍 

About friday: did we already made a final decision on that? Wasn't sure which is why I didn't mention it...

**Comment by FWirtz** [comment]
@jonashering Yes, I think we said that we'll do the Friday event anyways as we'll be @ dschool anyways. If nobody comes it'll be just us drinking beer which is alright as well, I guess.
@jak-ing @lheilmann correct me if I am wrong please

**Comment by annkatrinkuessner** [comment]
@FWirtz how about discussing that with the whole team on thursday? Last thing I heard was that we wanted to discuss the friday event and haven't decided on it yet

**Comment by jonashering** [comment]
@FWirtz Concerning the 22h period of hacking (this was one of the reasons for bringing the end of hacking forward): Regarding all announcements were made with this time frame, I'd suggest we just ignore it's 23h hours now. I guess no one will notice anyways 😄 

Or would you fix that?

**Comment by lheilmann** [comment]
Discussion on thursday sounds amazing. 👍

**Comment by jak-ing** [comment]
The Pre-Event and HackHPI headlines are kind of hard to see, what about using accent color `#ff8a00` which we've used before above?
image

**Comment by FWirtz** [comment]
@jak-ing awesome idea!

**Pull request merged**
