### PR TITLE
Add tableau as giga partner

### PR DESCRIPTION
**Pull request by FWirtz**
Tweak style.css, as tableau logo would seem tiny compared to SAP due to its vertical nature

Add resized SAP and tableau logo

Add tableau partner information

### CODE REVIEW

**Comment by FWirtz** [comment]
@jak-ing I can't rn, if you can do so feel free to, otherwise let's open an issue for that and try to get the logo on their quickly, it's been a full week now... 🚀

**Comment by jak-ing** [comment]
I was on holiday. ;) I'll change it and merge.

**Comment by FWirtz** [comment]
thanks for merging @jak-ing!

I just had a look https://hackhpi.org/#sponsors, sounds quite great already.
Tried making the giga partner logos a little smaller though (`height: 200px`), looks imo a little better.

What do you think? Do you think we can leave it as is or should we tweak it a little further?

**Comment by jak-ing** [comment]
Huh, but setting `height: 200px` makes them bigger?! 
Generally, I don't really care. I think it looks fine as is.

**Comment by FWirtz** [comment]
@jak-ing not for me, no? Currently it's `250px` height 😧 
Ok let's leave it as is for now.

**Pull request merged**
