### PR TITLE
Add FAQ item for PET Free

### LINKED ISSUE #72: Make P.E.T. Free visible and noticeable
Ich denke wir sollten sobald wie möglich auf der Website sichtbar machen, dass es sich um ein PET Free Event handelt. Im Scope dieses Issues meine ich textuell, so weit oben wie möglich.

### PR DESCRIPTION
**Pull request by lheilmann**
Closes #72

### CODE REVIEW

**Comment by jak-ing** [comment]
I think a statement is missing that HackHPI will be a PET free event.
Do we really want to collect and store the bottles for the duration of the event? Seems like quite the hassle to me.

**Comment by lheilmann** [comment]
@jak-ing I think honestly we have to, because some people will not read this. We we might not have to point out his on the website.

**Comment by lheilmann** [comment]
@jak-ing Better now? Short but enough?

**Comment by jak-ing** [comment]
Oh sorry, more specifically I meant storing the bottles might pose a problem. Just collecting them at the entrance is fine in my opinion.

**Pull request merged**
